ご支援者様no追加
orchestra-canvas-tokyo/homepage pull request #33
Opened 2024-12-27 15:11 UTC by Ueda-Yuto

2024-12-27 15:20 UTC, Ueda-Yuto commented
@horn553 こちらレビューお願いします。

2024-12-28 04:22 UTC, horn553 requested changes
LGTM……ではあったのですが、ちょうど今追加があったご支援者様、企業名の順序についても追加で対応いただけますとたすかります🙏

2024-12-28 14:20 UTC, Ueda-Yuto commented
@horn553 
対応しました。
要件通りかご確認いただきたいですmm

2024-12-28 23:58 UTC, horn553 approved these changes
LGTM!
![17354302969784236395697463757622](https://github.com/user-attachments/assets/9572ee45-c404-49b9-ae78-bac589fde0e1)

2024-12-29 00:44 UTC, merged